db.type=h2

h2.jdbc.driver=org.h2.Driver
h2.jdbc.url=jdbc:h2:file:./data/student_db;MODE=MySQL;DATABASE_TO_UPPER=false;AUTO_SERVER=TRUE
h2.jdbc.username=sa
h2.jdbc.password=

mysql.jdbc.driver=com.mysql.cj.jdbc.Driver
mysql.jdbc.url=jdbc:mysql://localhost:3306/student_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
mysql.jdbc.username=root
mysql.jdbc.password=your_password_here
